name: auto-revs

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v2

      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Create fake list of PR reviewers
        run: |
          python create_rev_list.py -o build/output

      - name: Install workflow dependencies
        run: npm install @octokit/rest

      - name: Update PR description
        uses: actions/github-script@v5
        with:
          script: |
            const { Octokit } = require("@octokit/rest");
            const { automatic_pr_update } = require('./.github/scripts/edit_pr.js');

            const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
            const pr_number = context.payload.number;
            const title = "### Automatic reviewers";

            await automatic_pr_update(octokit, github, context, title);
