name: auto-revs-2

on:
  workflow_dispatch:
  # pull_request:
  #   branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v2

      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Use pygithub to show data from this PR
        run: python smtb.py
