name: auto-revs

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v2

      - name: Update PR description
        uses: actions/github-script@v5
        with:
          script: |
            console.log(`Hola`);
            const response = await github.request(`/repos/{owner}/{repo}/pulls/{pull_number}`, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            console.log("Response status: ", response.status);
            console.log("Response body: ", response.body);
            console.log("Full response:");
            console.dir(response);
