name: auto-revs

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v2

      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Create fake list of PR reviewers
        run: |
          python create_rev_list.py -o build/output

      - name: Update PR description
        uses: actions/github-script@v5
        with:
          script: |
            const getNewBody = require('./.github/scripts/edit_pr.js');
            const new_body = getNewBody(github, context);
            console.log("new_body:", new_body);
            console.log("context.issue.number:", context.issue.number);
            console.log("context.issue.body:", context.issue.body);
